### ISSUE TITLE
Call to a member function insert() on boolean

### ISSUE THREAD

**Issue by mihaikelemen** [php-gettext/Gettext#228]
Scanning PHP code fails on v4.7 for the this type of translation `__("Foo %s", "bar")` 

This is working on v4.6.3

```
PHP Fatal error:  Uncaught Error: Call to a member function insert() on boolean in /vendor/gettext/gettext/src/Utils/FunctionsScanner.php:77
Stack trace:
#0 /vendor/gettext/gettext/src/Extractors/PhpCode.php(68): Gettext\Utils\FunctionsScanner->saveGettextFunctions(Array, Array)
#1 /vendor/gettext/gettext/src/Extractors/PhpCode.php(51): Gettext\Extractors\PhpCode::fromStringMultiple('<?php\nnamespace...', Array, Array)
#2 /vendor/gettext/gettext/src/Extractors/Extractor.php(18): Gettext\Extractors\PhpCode::fromString('<?php\nnamespace...', Object(Gettext\Translations), Array)
#3 [internal function]: Gettext\Extractors\Extractor::fromFile('/file_path/en_US/messages...', Object(Gettext\Translations), Array)
#4 /vendor/gettext/gettext/src/Translations.php(174): call_user_func('Gettext\\Extract...', '/file_path/en_US/messages...', Object(Gettext\Translations), Array)
#5 file_path: Gettext\Translations->__call( in /vendor/gettext/gettext/src/Utils/FunctionsScanner.php on line 77

```

**Comment by oscarotero** [comment]
Ok, I guess this is a bug introduced in #223 
@briedis could you please fix this? I don't have free time these days.

**Comment by briedis** [comment]
I'll check it out

**Comment by briedis** [comment]
@mihaikelemen Could you provide more info?

1. Can you give me a code example that is failing?
2. What is the __ function, why does it have two arguments in your example? Is that a domain, context method?
3. Can you show the function configuration - which function is considered which?

By default, __ should have only one argument:
![image](https://user-images.githubusercontent.com/500491/66939127-2413c680-f04b-11e9-99a4-90b635c82081.png)

**Comment by mihaikelemen** [comment]
Hi @briedis ,

Sorry for the late response. I'm using this approach with the second argument for quite a while, based on the docs (see bellow). It is a handful approach.

![Selecție_20191018](https://user-images.githubusercontent.com/17508016/67082425-ccd43a00-f1a1-11e9-8b84-85809cb6e291.png)

Mihai

**Comment by mihaikelemen** [comment]
This the actual code (part of it) that generates the po file for a given locale (in this case `ro_RO`)

~~~php
$files->files()
->name('/(.*)\.(tpl|php)/')
->depth('>=1')
->in($dirs);

$translations = new Translations();
$translations->setLanguage('ro_RO');
$translations->setDomain('messages');

# locale directory path
$dir = sprintf('%s%s/', $config->get('environment.locales'), 'ro_RO');
$potfile = sprintf('%s%s.po', $dir, $translations->getDomain());

if (!$filesystem->exists($dir)) {
    $filesystem->mkdir($dir, 0755);
    $filesystem->touch($potfile);
}

foreach ($files as $file) {
    $translations->addFromPhpCodeFile($file->getPathname());
}

if ($filesystem->exists($potfile)) {
    $translations->mergeWith(Translations::fromPoFile($potfile));
}

$translations->toPoFile($potfile);
~~~

**Comment by briedis** [comment]
Sorry @mihaikelemen for the delay, but I managed to run into this issue on my own too. A PR is created for the v4 branch. Actually the code to reproduce the issue was much simpler - just scan a file for one domain, but the file contains a single pgettext call without any strings from the domain you are searching for.

**Comment by mihaikelemen** [comment]
Hi @briedis ,
Thanks for your response. For now I'm using 4.6.3 until otherwise; eventually I will upgrade my code to run with the newer v5 branch.

Mihai
