### ISSUE TITLE
Cannot use Translator with .po files

### ISSUE THREAD

**Issue by Stephirio** [php-gettext/Gettext#237]
I tried to do this in my code
`use Gettext\Translator;
$t = new Translator();
$t->loadTranslations('locales/en.po');
echo $t->gettext('hi'); 
$t->register();
echo __('hi');`
but i get nothing

**Comment by oscarotero** [comment]
To use `Translator`, you have to export the .po file to PhpArray format.

```php
$translations = Translations::fromPoFile('locales/en.po');
$translations->toPhpArrayFile('locales/en.php');

//load the php array in the translator:
$t->loadTranslations('locales/en.php');
```

Here's more info: https://github.com/php-gettext/Gettext#translator

**Comment by Stephirio** [comment]
> To use `Translator`, you have to export the .po file to PhpArray format.
> 
> ```
> $translations = Translations::fromPoFile('locales/en.po');
> $translations->toPhpArrayFile('locales/en.php');
> 
> //load the php array in the translator:
> $t->loadTranslations('locales/en.php');
> ```
> 
> Here's more info: https://github.com/php-gettext/Gettext#translator

Thank you very much! Sorry my ignorance but I'm trying to learn. Anyway you answered very fast!

**Comment by Stephirio** [comment]
Srry, with the last update I encountered another error:
`Fatal error: Uncaught InvalidArgumentException: '/app/languages/it.po' is not a valid file in /app/vendor/gettext/gettext/src/Extractors/Extractor.php:37 Stack trace: #0 /app/vendor/gettext/gettext/src/Extractors/Extractor.php(16): Gettext\Extractors\Extractor::getFiles('/app/languages/...') #1 [internal function]: Gettext\Extractors\Extractor::fromFile('/app/languages/...', Object(Gettext\Translations), Array) #2 /app/vendor/gettext/gettext/src/Translations.php(182): call_user_func('Gettext\\Extract...', '/app/languages/...', Object(Gettext\Translations), Array) #3 [internal function]: Gettext\Translations->__call('addFromPoFile', Array) #4 /app/vendor/gettext/gettext/src/Translations.php(161): call_user_func_array(Array, Array) #5 /app/app.php(20): Gettext\Translations::__callStatic('fromPoFile', Array) #6 {main} thrown in /app/vendor/gettext/gettext/src/Extractors/Extractor.php on line 37`
Can you help me please?
