### ISSUE TITLE
Gettext\Loader\PoLoader doesn't exist

### ISSUE THREAD

**Issue by Stephirio** [php-gettext/Gettext#239]
When I try to use this code:
```
require_once __DIR__ . "/vendor/autoload.php";

use Gettext\Loader\PoLoader;

$loader = new PoLoader();

$dir = "/app/";

$t = $loader->loadFile($dir . "languages/it.po");

print_r($t . "YE::::);
```
it doesn't show anything on the page. Also "YE:::::" doesn't show up. 

Sorry for ignorance, I'm a beginner of PHP.

**Comment by oscarotero** [comment]
The code is wrong, you miss the final quote in `print_r($t . "YE::::);`

**Comment by Stephirio** [comment]
> 
> 
> The code is wrong, you miss the final quote in `print_r($t . "YE::::);`

Oh, sorry, I'm a noob.

**Comment by Stephirio** [comment]
I have one more question. How can I get a translation (for example "Hi") from the $t variable? 
Can i register ($t->register) it?
