### ISSUE TITLE
Wrong CHANGELOG link in release notifications

### ISSUE THREAD

**Issue by mlocati** [php-gettext/Gettext#243]
Just a minor issue, but still...

I just received the email notification about the new 8.4.2 version (you can watch "Releases only" in GitHub).

The link to the CHANGELOG file is wrong. Here's the HTML source of the email notification:
```html
<p>See <a href="/php-gettext/Gettext/blob/v4.8.2/CHANGELOG.md">CHANGELOG</a></p>
```

**Comment by oscarotero** [comment]
Why do you think it's wrong? This link is generated automatically by github. I only write: 

```md
See [CHANGELOG](CHANGELOG.md)
```

And github completes the url with the full path of the file in the tag.

**Comment by mlocati** [comment]
> Why do you think it's wrong?

Because when I click on the link in the email I receive, the browser tries to navigate to `/php-gettext/Gettext/blob/v4.8.2/CHANGELOG.md`, which is missing the protocol and the host name.


> And github completes the url with the full path of the file in the tag.

Yep, but the email notifications are wrong.

[Here's the email I received](https://github.com/php-gettext/Gettext/files/3911015/php-gettext_Gettext.Release.v4.8.2.-.4.8.2.zip): unzip it and open it with an EML viewer (like Thunderbird), or with a text editor to see the html.

**Comment by oscarotero** [comment]
I see.
It looks more a Github issue (of course, I can type the full url, but it's a bit harder). Thanks for notify this.

**Comment by oscarotero** [comment]
I just released a new version with the full url of CHANGELOG. Feel free to reopen this if the link still failing.

**Comment by mlocati** [comment]
Thanks! I submitted this issue to the GitHub support team and they forwarded it to the tech team, so it's up to them now 😉
