### ISSUE TITLE
Multi line strings: Wrong behaviour with \n

### ISSUE THREAD

**Issue by vielhuber** [php-gettext/Gettext#244]
Hello!

When I create a new translation with.
```
        $translation = Translation::create(null, "foo\nbar");
        $translation->translate("bar\nbaz");
        $this->translations->add($translation);
```

I end up with a PO file that looks like this:
```
msgid ""
"foo"
"bar\n"
msgstr ""
"bar"
"baz\n"
```

The expected behaviour should be:
```
msgid ""
"foo\n"
"bar"
msgstr ""
"bar\n"
"baz"
```

- Why is always a \n added on the last line?
- The lib detects the multiline strings but strips the \ns for each line in between

**Comment by oscarotero** [comment]
Hi, @vielhuber 
Yes, you're absolutelly right, this a bug. Sorry about that.
I've released a patch version with a fix.
Thanks

**Comment by vielhuber** [comment]
Very good, it works.
Thank you for this awesome lib.
