### ISSUE TITLE
Access to Comments object

### ISSUE THREAD

**Issue by xordiv** [php-gettext/Gettext#247]
I want to delete one comment in Comments object or replace it, but Comments class has no methods for it. And Translation class has no methods for setting up a new Comments object.
How I can replace a comment? Maybe is there a PHP trick for it?

**Comment by oscarotero** [comment]
Mmmm, you're right, there's no way to remove comments!! (I've never need it :) And the same happens with flags.

I'm implementing this:

```php
$comments->delete('This is a comment');
```

and let you know when it's shipped.
Thanks for notify!

**Comment by oscarotero** [comment]
v5.3.0 released

**Comment by vielhuber** [comment]
Very cool, thank you @oscarotero.
