### ISSUE TITLE
Description is not set when generating files

### ISSUE THREAD

**Issue by NathanBnm** [php-gettext/Gettext#253]
I noticed that you didn't added the description to the PO files header in the PO Generator.
Would you mind to add that?

**Comment by oscarotero** [comment]
Yes, I forgot that. Just commited a change with this. Can you test if it works fine now before release a new tag?

**Comment by NathanBnm** [comment]
@oscarotero this is working fine. Please just add one extra line between the description and the flags lke that: `$lines[] = "#";`

**Comment by oscarotero** [comment]
Ok, done and released.

**Comment by NathanBnm** [comment]
Thanks
