### ISSUE TITLE
Subsequent loadFile fails

### ISSUE THREAD

**Issue by vielhuber** [php-gettext/Gettext#257]
```php
<?php
require_once(__DIR__ . '/vendor/autoload.php');
use Gettext\Loader\PoLoader;
use Gettext\Generator\PoGenerator;
use Gettext\Generator\MoGenerator;
use Gettext\Translation;
use Gettext\Translations;

// setup
$poLoader = new PoLoader();
$poGenerator = new PoGenerator();
file_put_contents('test.po', '');
$translations = $poLoader->loadFile('test.po');
$translation = Translation::create('foo', 'bar');
$translations->add($translation);
$poGenerator->generateFile($translations, 'test.po');

// load again
$poLoader = new PoLoader();
$poGenerator = new PoGenerator();
$translations = $poLoader->loadFile('test.po');
var_dump(count($translations->getTranslations())); // this returns "0"
```

Fix (Generator.php):

```php
    public function generateFile(Translations $translations, string $filename): bool
    {
        $content = $this->generateString($translations);

        $res = file_put_contents($filename, $content) !== false;
        clearstatcache();
        return $res;
    }
```

Reason:  https://www.php.net/manual/de/function.filesize.php#101996

**Comment by vielhuber** [comment]
The fix above is not sufficient: This has to be done inside ```loadFile```.

**Comment by ideag** [comment]
Hi @oscarotero, I'd like to help fixing this, as we seem to have issues when we try to modify the same PO file several times.
Is there any specific reason for using `fopen`/`fread` in the `readFile` method instead of `file_get_contents`? In our experience using file_get_contents solves the issues for us, but maybe I'm not aware of something?

**Comment by oscarotero** [comment]
Hi @ideag 
Sorry, I missed this. Yes, you can use `file_get_contents`, I don't remember any special reason to use `fopen`.
Thanks for your contribution!

**Comment by ideag** [comment]
I'll make a PR 👍
