### ISSUE TITLE
Feature Request: WordPress gettext functions support for scanner

### ISSUE THREAD

**Issue by hirasso** [php-gettext/Gettext#268]
Hi there! Just gave your package a test run with my WordPress theme – it detects `__()` just well, but ignores other functions like `_e()` (=echo) or `_x()` (gettext with context). Would it be possible to add support for these functions?

**Comment by oscarotero** [comment]
You can configure the php-scanner with the other functions names. For example:

```php
$scanner = new PhpFunctionsScanner();
$scanner->setFunctions([
    "__" => "gettext",
    "_e" => "gettext",
    "_x" => "pgettext",
])
```

**Comment by hirasso** [comment]
Great, thank you!!
