### ISSUE TITLE
Handling of defective .po files

### ISSUE THREAD

**Issue by jonasraoni** [php-gettext/Gettext#282]
If I try to load a `.po` file with the following content:

```po
msgid "message.id"
msgstr "this line is ok"
this line is missing the initial quote"
```

It works, but the defective line is ignored. It would be great if the package could log a warning or fail with an exception (this could be probably configurable with a "strict mode", disabled by default to keep the compatibility).

I'll take a look in the code, perhaps I can contribute with another PR if you think the idea is ok.

**Comment by oscarotero** [comment]
Yeah, it makes sense to me. PR is appreciated, thanks!

**Comment by jonasraoni** [comment]
Great, I'll take a look at the code and `.po` format, which is short and try to come up with something generic.
My objective is to also be able to use the package to validate/identify broken files.

**Comment by jonasraoni** [comment]
FYI, I've checked the `.po` format and I think it's too superficial, it's missing a lot of small details 🤔
I'll address the things that I saw and come up with a proposal.

**Comment by jonasraoni** [comment]
- #283
