### ISSUE TITLE
what is the equivilent of v4 Gettext->register() in v5?

### ISSUE THREAD

**Issue by lachlan-00** [php-gettext/Gettext#286]
I'm sorry i have to raise this issue but i don't really understand how this code works.

Ampache loads the MO and uses __() for translations using a helper function so migration should be simple?

I've looked at the  the guide
https://github.com/php-gettext/Gettext/wiki/Migration-from-v4-to-v5

But i can't see a function in the v5 code that functions the same as register()

```
function load_gettext()
{
    $lang   = AmpConfig::get('lang');
    $mopath = __DIR__ . '/../../locale/' . $lang . '/LC_MESSAGES/messages.mo';
    if (file_exists($mopath)) {
        $gettext      = new Translator();
        $translations = Gettext\Translations::fromMoFile($mopath);
        $gettext->loadTranslations($translations);
    }
    $gettext->register();

    return true;
} // load_gettext
```

I'm assuming all i need to do is load the MO file using Gettext\Loader\MoLoader and then register them somehow to the __() function but the wiki page is about loading and generating files and i don't really understand.

**Comment by oscarotero** [comment]
In Gettext v5, the translator was moved to a different package: https://github.com/php-gettext/Translator#translator-functions

**Comment by lachlan-00** [comment]
excellent! thank you.

**Comment by lachlan-00** [comment]
@oscarotero do you mind if i edit the wiki page there to provide that info as well?

**Comment by oscarotero** [comment]
No problem. Do you need permissions or something?

**Comment by lachlan-00** [comment]
No, I was just asking out of politeness. Thanks for being so responsive to my queries and I'll update the wiki tomorrow. :)
