### ISSUE TITLE
[Question] Simplest way to promote items in a Translations object to a subclass?

### ISSUE THREAD

**Issue by rulatir** [php-gettext/Gettext#292]
Use case: I receive a `Translations` object `$original` containing vanilla `Translation` items, and I must return a `Translations` object `$extended` with the following properties:
 - all "global" properties and metadata (**even custom ones!**) not pertaining to individual `Translation` items must be the same as in the `$original`
 - every `Translation` item must be replaced by an instance of `ExtendedTranslation` holding the same information (as well as some extra information specific to `ExtendedTranslation`).

This was easy while `->exchangeArray()` was available. Now that it is gone, it seems I must do this:

 - `$extended = clone $original;`
 - `getTranslations()`
 - iterate to remove them from `$extended` (O(n^2)?)
 - iterate again to promote `Translation` items to `ExtendedTranslation` objects and `add()` them to `$extended`

Is there a simpler way with current API?

`Translations` is a collection object, and I believe it should provide fully featured collection API: `map()`, `filter()`, `removeAll()` etc.

**Comment by oscarotero** [comment]
Probably something like this?

```php
$extended = clone $original;

foreach ($extended as $translation) {
    $extended->add(new ExtendedTranslation($translation));
}
```

If the old and new translations has the same id, it will be overrided, so you don't need to remove the first.

Another way is creating the `ExtendedTranslations` class:

```php
class ExtendedTranslations extends Translations {
    public static function create(Translations $traslations) {
        $new = new static();
        $new->description = $translations->description;
        $new->headers = $translations->headers;
        $new->flags = $translations->flags;
        $new->translations = array_map(function ($translation) {
            return new ExtendedTranslation($translation))
        }, $translations->getTranslations());

        return $new;
    }
}

$extended = ExtendedTranslations::create($original);
```
