### ISSUE TITLE
How do I configure to scan files for my own custom funtions

### ISSUE THREAD

**Issue by mmethner** [php-gettext/Gettext#294]
This question is similar to https://github.com/php-gettext/Gettext/issues/128 but relates to the current version. In my code I use a global function call `\Trans::late('text to translate goes here')`. I want to scan all my templates and create a *.po file from it. I can not figure out, how I configure the tool to use my` \Trans::late()` function to get all texts to translate. Is that possible?

**Comment by oscarotero** [comment]
You have to install the PHP Scanner package https://github.com/php-gettext/PHP-Scanner/ that scan the code and search for the defined functions.

To configure the functions, use the `setFunctions` function.
The default values are here: https://github.com/php-gettext/PHP-Scanner/blob/master/src/PhpScanner.php#L16

```php
//Create a new scanner, adding a translation for each domain we want to get:
$phpScanner = new PhpScanner(
    Translations::create('domain1'),
    Translations::create('domain2'),
    Translations::create('domain3')
);

//Set a default domain, so any translations with no domain specified, will be added to that domain
$phpScanner->setDefaultDomain('domain1');

// Configure the functions
$phpScanner->setFunctions([
  // Your functions here
]);
```
