### ISSUE TITLE
PHP 8.3 Support

### ISSUE THREAD

**Issue by renemattis74** [php-gettext/Gettext#298]
Dear Developers,

i love this tool and i use it in the most of my PHP projects.

**Could you tell me when PHP 8 will be supported?**

Thanx a lot :-)

**Comment by oscarotero** [comment]
PHP 8 is already supported but I just added test for 8.2 and 8.3 and it fails.
Unfortunately, I cannot install php 8 in my computer so I cannot fix these issues.

If anyone want to help with this, I'd really appreciate it.

**Comment by renemattis74** [comment]
Thanks a lot, that sound good ... Here the error message on PHP 8.3

[Exception] Invalid gettext function in .... Some required arguments are not valid in .../vendor/gettext/gettext/src/Scanner/CodeScanner.php on line 148 Stack Trace: - .../vendor/gettext/gettext/src/Scanner/FunctionsHandlersTrait.php:15 - [internal]:?? - .../vendor/gettext/gettext/src/Scanner/CodeScanner.php:81 - .../vendor/gettext/gettext/src/Scanner/CodeScanner.php:67 - .../vendor/gettext/gettext/src/Scanner/Scanner.php:45

**Comment by renemattis74** [comment]
I have found the mistake (wrong translation string in a PHP file). 
Everything is fine under PHP 8.3. 

Thanks a lot !

**Comment by pedro-mendonca** [comment]
Hi @oscarotero 
I think I've found the culprit: it's `ksort()` [here](https://github.com/php-gettext/Gettext/blob/master/src/Generator/MoGenerator.php#L48).
Since PHP 8.2 that ksort() deals with int/string keys differently.
https://php.watch/versions/8.2/ksort-SORT_REGULAR-order-changes

Up to PHP 8.1 the int keys are sorted last.
From PHP 8.2 the int keys are sorted first.

What is the main intent of this ksort here? You probably want to treat all keys as strings, right?

**Comment by oscarotero** [comment]
Hey, @pedro-mendonca 
Yes, in this case the keys are the original strings and the idea is to sort the translations before to generate the .mo file.

Do you mind to create a PR?

**Comment by pedro-mendonca** [comment]
I see. The issue is that ksort is treating the key (string) '123456' as int.
I'll do a PR.

**Comment by pedro-mendonca** [comment]
The strings that are numbers should be sorted before letters right?
If so, the binary test file must be also changed.

**Comment by pedro-mendonca** [comment]
About the idea of sorting, usually the .po files keep the order of appearance in the source code, then editors like Poedit allow sort by any original or translation.
Why sort by original in the first place while generating .mo binaries?
Wouldn't it be better to just keep the source order?

**Comment by oscarotero** [comment]
Tbh, this code was written long time ago, (and maybe not by me).

Perhaps the order makes find entries faster. Or maybe it's to ensure than the same translations, in different order produce the same binary file (scanning files in different OS or environments can change the order in which files are read).

**Comment by pedro-mendonca** [comment]
From performance point of view I don't see it would be different.
But, the argument about the binary produced being the same independently of the source order might be relevant.

**Comment by pedro-mendonca** [comment]
@oscarotero let me know if the PR is ok for you :)
