### ISSUE TITLE
Planned next release to fix PHP 8.4 warnings

### ISSUE THREAD

**Issue by MyIgel** [php-gettext/Gettext#301]
Hi, is there a timeline / idea for when a new release might be available where #300 is integrated?
That would help many dev envs that convert warnings to exceptions ^^

**Comment by oscarotero** [comment]
New version 5.7.2 released with support for php 8.4
Thanks for the heads up!

**Comment by MyIgel** [comment]
Thank you for the quick reaction, it works great! <3
